### PR TITLE
Filters: Add an author filter

### LINKED ISSUE #283: React UI: Implement pull author url params
In the new React UI, the author url params don't work. 

Old frontend: https://pulldasher.cominor.com/?assigned=dependabot[bot] works
New frontend: https://pulldasher.cominor.com/frontend/?assigned=dependabot[bot] doesn't work

### PR DESCRIPTION
**Pull request by danielbeardsley**
Just like the Repo filter from #277, but for pull authors.
CR this one commit at a time.

image

Closes #283

### CODE REVIEW

**Comment by danielbeardsley** [comment]
deploy_block :+1:  on #277 going out because this is based on that branch.

**Comment by deltuh-vee** [comment]
dev_block ✊
The autofocus on the menu is making it difficult to close the menu. Clicking away also doesn't do anything.
https://user-images.githubusercontent.com/5289715/162257479-b3cc7805-7e3e-423a-bcd1-41b38ebf8d99.mp4

**Comment by danielbeardsley** [comment]
> The autofocus on the menu is making it difficult to close the menu. Clicking away also doesn't do anything.

I'm having a tough time understanding here. The video seems to just show you scrolling up and down. I did notice that if you scroll down, Chakra will autoscroll back up so the menu is in view. A little odd that it does it ~1s after you stop scrolling instead of immediately, but it doesn't seem to impede the functionality at all. Clicking off works fine for me... curious. Let's get together so you can show me.

**Comment by deltuh-vee** [comment]
dev_block ✊ 
So it looks like the whitespace below pull requests isn't capturing click events, which is why I wasn't able to click away when there were a small number of pulls shown.

**Comment by sctice-ifixit** [comment]
CR :rose: Sweet!

**Comment by deltuh-vee** [comment]
QA 🎬 
* Pulls can now be filtered by Authors
* Author filter menu can now be exited by clicking in whitespace

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 19ce89e

**Comment by danielbeardsley** [comment]
I've closed the other pull and made the suggested fixes (from @andyg0808 ) here this pull significantly refactored the menu filter code.

**Comment by danielbeardsley** [comment]
un_deploy_block :+1:  other pull is folded into this one.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through e4d90ad

File: frontend/src/filter-menu.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export function FilterMenu({urlParam, buttonText, extractValueFromPull}: FilterM
              <MenuItemOption
                 key={value}
                 value={value}>
-                {value} ({valueToPullCount.get(value) || 0})
+                {value} ({valueToPullCount[value] || 0})
```
Comment (sctice-ifixit) [inline frontend/src/filter-menu.tsx:56]: I think it would be a little nicer to leave the count off here and show this item grayed out. I see little benefit in clicking a filter we know will yield zero results (at least, at present), so I think it makes sense to remove some visual weight relative to other items.

**Comment by sctice-ifixit** [comment]
CR :flags:

**Comment by erinemay** [comment]
QA 👍 
- Author filter works as expected individually and combined with repo filter
- Click events outside of the dropdown closes it

I think these conversations are happening in other pulls or issues, so I'll deploy_block 🌵 here and @danielbeardsley feel free to un-deploy-block it.
1. The number of pulls associated with each author doesn't reflect the number of pulls displayed when filtering by that author while showing all repos.
image

2. When filtering on the old ui, the column counts are adjusted to show current, filtered counts 
image

**Comment by erinemay** [comment]
>When filtering on the old ui, the column counts are adjusted to show current, filtered counts

I was thinking of https://github.com/iFixit/pulldasher/pull/289, but it looks like that only applies to the nav bar.

**Comment by danielbeardsley** [comment]
> The number of pulls associated with each author doesn't reflect the number of pulls displayed when filtering by that author while showing all repos.

If we just used a count of "displayed pulls" all the unchecked items would have 0s which isn't that useful.

> When filtering on the old ui, the column counts are adjusted to show current, filtered counts

Fixed in #290

**Comment by danielbeardsley** [comment]
un_deploy_block :+1:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 2ce8db7

**Comment by sctice-ifixit** [comment]
Looks like there are a few TS errors to be cleared up.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 3373753

**Comment by jordycosta** [comment]
When testing this, I noticed that every author is marked as filtered initially. I think that this would make filtering by a pull author more difficult since there is no way to uncheck all the authors that are already selected.

I suggest that either:

> the `Show All` action could toggle on/off

or

> using the Author filter would have no authors selected at first, which allows someone to select a specific author by pull instead of having to deselect each author currently being shown.

---

### Screen Capture:

author_filter

File: frontend/src/filter-menu.tsx (hunk 1 above)
Comment (danielbeardsley) [reply frontend/src/filter-menu.tsx:56]: When building a filter, you may want to include authors that don't *currently* have any pulls but you'd like to include them. Our team uses a link that includes `author=.....` a big list. Not all of them always have pulls open. FYI, 0s will pretty much only be present if there are authors included in the url that don't have open pulls.

**Comment by danielbeardsley** [comment]
Thank you @sterlinghirsh and @sctice-ifixit for the good suggestions. It's been implemented. Things now start out as *not* checked, so clicking one goes from *everything* to *just that thing*

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 615cc09

**Comment by jordycosta** [comment]
QA 🟢 

No author is selected initially ☑️ 
`Show All` unchecks any selected author(s) ☑️ 

---

**Suggestions:**

Move the bar previously above `Show All` to the top

bar

---

Additional Notes:

1. It appears that the counter for each author isn't 100% accurate
> For example: some users are shown as having pulls, but when selecting them no pulls appear

**Comment by danielbeardsley** [comment]
> It appears that the counter for each author isn't 100% accurate

I think this is because this count is of *all* open pulls. This includes those filtered out for other reasons (Cryo, search, repo filter, ...)

**Comment by danielbeardsley** [comment]
I'm gonna merge this cause I implemented Shawns suggestion and he'll be on a plane for a while.
