### PR TITLE
QA Column: exclude pulls failing CI

### LINKED ISSUE #282: React UI: Exclude failed CI pulls from QA column
In the new React UI, pulls that have failed CI checks are showing up in the QA column. They should be excluded.

### PR DESCRIPTION
**Pull request by danielbeardsley**
Generally, if a pull is failing CI, we'll need to do more work on it
and QA should spend there energy elsewhere.

So, we'll hide pulls that fail CI from the QA Column.

Closes #282

### CODE REVIEW

File: frontend/src/pulldasher/index.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ export const Pulldasher: React.FC = function() {
    const pullsReady = pulls.filter(pull => pull.isReady() && pull.isCiRequired());
    const pullsDevBlocked = pulls.filter(pull => pull.getDevBlock());
    const pullsNeedingCR = pulls.filter(pull => !pull.isCrDone() && !pull.getDevBlock());
-   const pullsNeedingQA = pulls.filter(pull => !pull.isQaDone() && !pull.getDevBlock());
+   const pullsNeedingQA = pulls.filter(pull => !pull.isQaDone() && !pull.getDevBlock() && pull.hasPassedCI());
```
Comment (ardelato) [inline frontend/src/pulldasher/index.tsx:14]: I am not sure if I am missing something when looking at how `hasPassedCI` works, but won't it return false if there are no build statuses or CI for the pull?

https://github.com/iFixit/pulldasher/blob/d6fc41cf37a86fd38e69ef8684e10b6dcf18606c/frontend/src/pull.ts#L66-L72

https://github.com/iFixit/pulldasher/blob/d6fc41cf37a86fd38e69ef8684e10b6dcf18606c/frontend/src/pull.ts#L113-L118

Comment (danielbeardsley) [reply frontend/src/pulldasher/index.tsx:14]: `[].every(() => false)` is true.  i.e. an empty array will *always* return true for `.every()`

image

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

Comment (ardelato) [reply frontend/src/pulldasher/index.tsx:14]: Ooooh sick! Thank you @danielbeardsley

**Review by ardelato — APPROVED** [review]
CR 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
Pulls that are failing CI are not shown in the QA column.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 1913dad
