### PR TITLE
QA column: Use custom sorting order

### LINKED ISSUE #280: QA column card order request
Order pulls in the QA column based on the following logic:
1. Full CR first/empty CR last
2. If same CR, order by age of pull (oldest first)
3. `External block` label at the very bottom
4. Currently being tested by others (`QAing` label) to the bottom (just above `external block` pulls)
5. Keep the exception that a user's own `QAing` label on a card will show up at the top of the column
6. Remove any ordering logic around Github milestones

### PR DESCRIPTION
**Pull request by danielbeardsley**
As specified in the issue, the order is broken down like this:

* QAing (by current user)
* Everything else
  * No external Block
    * Not QAing
      * Pulls with completed CR
        * Sort by oldest first 
      * Pulls needing more CR
        * Sort by oldest first 
    * QAing
  * External Block

Closes #280

### CODE REVIEW

File: frontend/src/pulldasher/sort.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+    compareBool(a.isMine(), b.isMine()) ||
+    // Pulls I have to CR/QA above those I don't
+    compareBool(a.hasOutdatedSig(getUser()), b.hasOutdatedSig(getUser())) ||
+    // Pulls I haven't touched vs those I have already CRed
+    compareBool(!a.hasCurrentSig(getUser()), !b.hasCurrentSig(getUser()))
+   );
+}
+
+function compareBool(a: boolean, b: boolean): number {
+   return +b - +a;
```
Comment (ardelato) [inline frontend/src/pulldasher/sort.ts:36]: TIL, ooh I didn't know you can just convert booleans to numbers like this

**Comment by cdcline** [comment]
CR 👍

File: frontend/src/pulldasher/sort.ts [hunk 2]
```diff
@@ -12,6 +12,26 @@ export function defaultCompare(a: Pull, b: Pull): number {
...
+      // Pulls with CR completed above those that need more
+      compareBool(a.isCrDone(), b.isCrDone()) ||
+      // Older pulls before younger pulls
+      a.created_at.localeCompare(b.created_at)
+   );
+}
+
+function isQAingByMe(pull: Pull): boolean {
+   const label = pull.getLabel('QAing');
+   return !!(label && label.user == getUser());
```
Comment (ardelato) [inline frontend/src/pulldasher/sort.ts:32]: Since you are already using `!!` can't we combine that with an optional chain to remove the first check on whether `label` is defined?

```
return !!(label?.user == getUser());
```

**Review by ardelato — APPROVED** [review]
CR 👍  with possible suggestion

**Comment by erinemay** [comment]
QA 👍 
Sorting is as described. 

I did a little meddling with the current pulldasher pulls (changed CR requirements, added and removed mine and others QAing label), and changed everything back.

**Comment by erinemay** [comment]
deploy_block ❓ on the number of pulls showing up in the QA column. I see 10 on pulldasher - main, 17 on the new frontend ui, and 12 on this branch when testing on pulldasher-dev. 

@danielbeardsley does this pull touch the logic on what lives in that column?

**Comment by danielbeardsley** [comment]
> . I see a discrepancy between the number of pulls in the QA column when I test with this branch vs master on pulldasher-dev.

Possible because this branch doesn't include #290. And no, this doesn't change the number of pulls, just the order.

un_deploy_block :+1:

**Comment by erinemay** [comment]
qa 🦢 order is as spec'd

File: frontend/src/pulldasher/sort.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+      // Pulls with CR completed above those that need more
+      compareBool(a.isCrDone(), b.isCrDone()) ||
+      // Older pulls before younger pulls
+      a.created_at.localeCompare(b.created_at)
+   );
+}
+
+function isQAingByMe(pull: Pull): boolean {
+   const label = pull.getLabel('QAing');
+   return !!(label?.user == getUser());
```
Comment (andyg0808) [inline frontend/src/pulldasher/sort.ts:32]: Won't the `==` always return a boolean?
```suggestion
   return label?.user == getUser();
```

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 8b0b906

**Comment by jordycosta** [comment]
QA 🟢 

Order is as followed in the spec:

    QAing (by current user)
    No external Block:
           Pulls with completed CR
               Sort by oldest first
           Pulls needing more CR
               Sort by oldest first
    Externally blocked pulls

---

### Testing Procedure:
1. Checkout | merge with [`qa-leader-list--remove-it`](https://github.com/iFixit/pulldasher/tree/qa-leader-list--remove-it)
2. Run the following script:
> `/home/ifixit/ifixit_scripts/update-pulldasher-dev --run . `
3. View the changes on https://pulldasher-dev.cominor.com/

---

### Screen Capture:

<details>
<summary> Toggle View </summary> <br>

sortQA
</details>

**Comment by ardelato** [comment]
CR 👍
