### PR TITLE
Hooks: deal with issue events about pull requests

### LINKED ISSUE #57: Pulldasher is incorrectly creating 'issues' from Pull Request webhooks
[`github-hooks--handle-issue-events-on-pulls`](https://github.com/iFixit/pulldasher/compare/github-hooks--handle-issue-events-on-pulls)

Entries in the `issues` table are being created for pull requests:

`select from_unixtime(date_created), number from issues inner join pulls using(number)`
image

[This doc](https://developer.github.com/v3/issues/) says we can look for a `pull_request` key to determine if an issue is a pull request.

This breaks chartio queries in unexpected ways, eg showing milestones that are closed as having open issues:

```
SELECT 	i.milestone_title AS 'Milestone', 
		c.`squad`, 
	   ROUND(SUM(i.date_closed > 0) / COUNT(*) * 100) as percent_done_now
FROM coders c
LEFT JOIN metrics.issues i ON (c.github_username = i.assignee) 
WHERE i.milestone_due_on > UNIX_TIMESTAMP() - 24 * 60 * 60 * 90 AND 
	  c.`squad` != 'Other'
GROUP BY c.squad, `Milestone`
ORDER BY MAX(i.milestone_due_on) ASC, c.squad;
 ```
image

### PR DESCRIPTION
**Pull request by danielbeardsley**
We've seen this in practice and the docs mention it; we can receive
issue events about pull requests. Thankfully they also mention how to
distiguish them. Previously, we didn't and would occasionally get
issues records created for pull requests (instead of records in the
pulls table).

CC @entendu

Note: there are a few other small refactorings in here too, go
commit by commit for CR.

Closes #57

### CODE REVIEW

File: controllers/githubHooks.js [hunk 1]
```diff
@@ -136,31 +113,16 @@ var HooksController = {
...
+   // Some of these events are also triggered on pull requests
+   var isPull = body.issue.pull_request;
+
+   var doneHandling = handleLabelEvents(body);
+
    switch(body.action) {
       case "opened":
          // Always do this for opened issues because a full refresh
          // is the easiest way to get *who* assigned the initial labels.
-         return refresh.issue(body.issue.number);
```
Comment (danielj41) [inline controllers/githubHooks.js]: Should this wait for `doneHandling` to resolve before calling `refreshPullOrIssue`?

It wouldn't change anything right now, since `handleLabelEvents` will return a fulfilled promise for this `body.action`.

**Comment by solflare** [comment]
CR :moon:

File: controllers/githubHooks.js (hunk 1 above)
Comment (danielbeardsley) [inline controllers/githubHooks.js]: Good point. Fixed.

**Comment by danielj41** [comment]
CR 👍

**Comment by solflare** [comment]
CR :moon:
